const diseaseMap ={
    "0": "Apple Apple scab",
    "1": "Apple Black rot",
    "2": "Apple Cedar apple rust",
    "3": "Apple healthy",
    "4": "Bacterial leaf blight in rice leaf",
    "5": "Blight in corn Leaf",
    "6": "Blueberry healthy",
    "7": "Brown spot in rice leaf",
    "8": "Cercospora leaf spot",
    "9": "Cherry (including sour) Powdery mildew",
    "10": "Cherry (including_sour) healthy",
    "11": "Common Rust in corn Leaf",
    "12": "Corn (maize) healthy",
    "13": "Garlic",
    "14": "Grape Black rot",
    "15": "Grape Esca Black Measles",
    "16": "Grape Leaf blight Isariopsis Leaf Spot",
    "17": "Grape healthy",
    "18": "Gray Leaf Spot in corn Leaf",
    "19": "Leaf smut in rice leaf",
    "20": "Orange Haunglongbing Citrus greening",
    "21": "Peach healthy",
    "22": "Pepper bell Bacterial spot",
    "23": "Pepper bell healthy",
    "24": "Potato Early Blight",
    "25": "Potato Late Blight",
    "26": "Potato healthy",
    "27": "Raspberry healthy",
    "28": "Sogatella rice",
    "29": "Soybean healthy",
    "30": "Strawberry Leaf scorch",
    "31": "Strawberry healthy",
    "32": "Tomato Bacterial spot",
    "33": "Tomato Early blight",
    "34": "Tomato Late blight",
    "35": "Tomato Leaf Mold",
    "36": "Tomato Septoria leaf spot",
    "37": "Tomato Spider mites Two spotted spider mite",
    "38": "Tomato Target Spot",
    "39": "Tomato Tomato mosaic virus",
    "40": "Tomato healthy",
    "41": "algal leaf in tea",
    "42": "anthracnose in tea",
    "43": "bird eye spot in tea",
    "44": "brown blight in tea",
    "45": "cabbage looper",
    "46": "corn crop",
    "47": "ginger",
    "48": "healthy tea leaf",
    "49": "lemon canker",
    "50": "onion",
    "51": "potassium deficiency in plant",
    "52": "potato crop",
    "53": "potato hollow heart",
    "54": "red leaf spot in tea",
    "55": "tomato canker"
}

export default diseaseMap;